# Global 
# define functions called in server.R


library(shiny)
library(htmltools)
library(shinyapps)
library(streamgraph)
library(dplyr)
library(tidyr)
library(rebird)
library(magrittr)
library(leaflet)
library(rgdal)
library(dplyr)
library(tidyr)
library(readr)
library(RColorBrewer)
library(lubridate)
library(jsonlite)
library(magrittr)


#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=4230K1kFQuLx-t+BrupJWuZNBv7ksp6gy54Quo4dmA7JmD4Bk00-n00Yn00SY03v-08vgkr7QFcoRDktPCE7SwUIDu

																					
																					#####  Generated by Paletton.com (c) 2002-2014
# COlor Palette:
palette <- c('#9D7A2D',
	     '#423EAA',
	     '#072953',
	     '#8088A1')
pal <- brewer.pal(11, name = 'Spectral')

secPal <- c('#072953', '#214C7E', '#123765', '#03244C', '#001E42')
streamPal <- c('#423EAA', '#D0D1D4',  '#5855A9', '#D0D1D4',  '#4C48A8', '#A3A7B3', '#3631B0', '#616D95', '#2721B8', '#354887')

# Stats data- more general things
lifeList <- function(data){ # life list-- # of species seeen  @^* Can be used as a filter for mapping where selected birds were seen.
	data %>% group_by(Common.Name) %>% tally()
} 


# Data to map--
# number of species per 'Submission'

submissionSpCount <- function(data){
	data %>% group_by(Submission.ID, Latitude, Longitude) %>% tally()
}

# DT global options-
options(
	DT.options = list(columnDefs = list(className = 'dt-center'), dom = 't')
	)



eBirdSpeciesStream <- function(data){
	# Display your personal eBird data in a stream plot summarized across a 'typical' year.
	# Idea-- add a control mechanism to select the 'scale' of the summary (month or day or even year for big ebird datasets)
	# Issue with passing a variable of 'monthly', 'weekly' or 'daily' to streamgraph.
	# data is summarized down to the calendar day (Month and Day of all years)
	data %>% 
		mutate(Date = mdy(Date)) %>% 
		separate(Date, into = c("Year", "Month", "Day"), remove = FALSE) %>%
		mutate(CalendarDay = mdy(paste(Month, Day, "2016",  sep = "-")), Monthly = mdy(paste(Month, "1", "2016")), 
		       Weekly = week(Date)) %>%  # try to fix weekly
		group_by_("Common.Name", 'Monthly') %>% 
		tally()%>% 
		mutate(n = n) %>% 
		streamgraph(key = 'Common.Name', value = n, date = 'Monthly') %>% 
		sg_legend(show = TRUE, label = 'Species') %>% 
		sg_fill_manual(values = streamPal)
}


